version: '3'

# Automated test compose file.

services:
  app:
    image: lochnerr/tftpd
    restart: "no"
    hostname: app.example.com
    volumes:
      - data:/var/tftpboot
    ports:
      - "69:69/udp"
  sut:
    image: lochnerr/tftpd
    command: /usr/local/bin/run-sut.sh
    restart: "no"
    hostname: sut.example.com
    volumes:
      - data:/var/tftpboot
    depends_on:
      - app

volumes:
  data:

